"""
42 RMF artifact templates required by FR-5.1 / FR-5.2.

The SRS references "all 42 artifact types listed in the master prompt" without
enumerating them. This list aggregates the 42 artifacts most consistently named
across NIST SP 800-37 Rev. 2, NIST SP 800-53 Rev. 5, DoDI 8510.01, and
AFI 17-101 to reach 42. Validate the set against your local AO and ISSM
guidance before treating any artifact as required.
"""

CATEGORIES = {
    "prep":     "Step 0 - Prepare",
    "categorize":"Step 1 - Categorize",
    "select":   "Step 2 - Select",
    "implement":"Step 3 - Implement",
    "assess":   "Step 4 - Assess",
    "authorize":"Step 5 - Authorize",
    "monitor":  "Step 6 - Monitor",
    "ongoing":  "Cross-step / continuous",
}


def _t(key, name, category, fmt, purpose, owner, inputs, approval,
       controls, evidence, criteria, emass, generator=None):
    return {
        "key": key,
        "name": name,
        "category": category,
        "category_name": CATEGORIES[category],
        "format": fmt,
        "purpose": purpose,
        "owner": owner,
        "inputs": inputs,
        "approval_path": approval,
        "control_mappings": controls,
        "evidence_expectations": evidence,
        "completion_criteria": criteria,
        "emass_location": emass,
        "generator": generator,  # internal name of the generator function, or None
    }


TEMPLATES = [
    # ---------- Step 0 - Prepare ----------
    _t("project_charter", "Project Charter", "prep", "docx",
       "Document mission, scope, schedule, and accountability for the RMF effort.",
       "ISSO", ["System mission", "Stakeholder list", "Target ATO date"],
       "ISSO drafts; ISSM reviews; AO acknowledges.",
       ["PM-1", "PL-2"],
       ["Signed charter document"],
       "Charter signed by ISSO and ISSM before Step 1 begins.",
       "Project Setup > Charter"),
    _t("stakeholder_matrix", "Stakeholder Matrix", "prep", "docx",
       "List every stakeholder with role, contact, and approval authority.",
       "ISSO", ["Org chart", "Role appointments"],
       "ISSO drafts; ISSM approves.",
       ["AC-2", "PM-2"],
       ["Matrix with role, name, contact, escalation path"],
       "All required RMF roles populated with current personnel.",
       "Project Setup > Stakeholders",
       generator="stakeholder_matrix"),
    _t("emass_setup_checklist", "eMASS Project Setup Checklist", "prep", "docx",
       "Confirm eMASS project record creation and required field population.",
       "ISSO", ["System metadata", "AO designation"],
       "ISSO completes; ISSM verifies.",
       ["CA-1"],
       ["Screenshot of eMASS project record", "Field-completion checklist"],
       "All eMASS mandatory fields populated; record visible to ISSM.",
       "Project Setup > eMASS Record"),
    _t("appointment_letters", "Appointment Letters (ISSO/ISSM/AO/SCA)", "prep", "docx",
       "Document formal appointment of each RMF role.",
       "Command", ["Role assignments"],
       "Commander signs.",
       ["PM-2", "AC-2"],
       ["Signed appointment letters on file"],
       "All four primary roles have current appointment letters.",
       "Personnel > Appointments"),

    # ---------- Step 1 - Categorize ----------
    _t("fips199_worksheet", "FIPS 199 Categorization Worksheet", "categorize", "docx",
       "Document Confidentiality, Integrity, Availability ratings per information type and overall.",
       "ISSO", ["Information types (NIST 800-60)", "Mission impact analysis"],
       "ISSO drafts; ISSM approves.",
       ["RA-2"],
       ["Per-info-type CIA ratings", "Overall categorization with rationale"],
       "Worksheet signed by ISSM, attached to SSP.",
       "Categorization > FIPS 199",
       generator="fips199"),
    _t("info_type_worksheet", "Information Type Worksheet (NIST 800-60)", "categorize", "xlsx",
       "Identify every information type processed and its standard impact recommendation.",
       "ISSO", ["Mission analysis", "Data inventory"],
       "ISSO drafts.",
       ["RA-2"],
       ["Information types listed", "Recommended impact per type"],
       "All information types identified and impacted per NIST 800-60.",
       "Categorization > Information Types"),
    _t("cnssi1253_worksheet", "CNSSI 1253 Worksheet (NSS only)", "categorize", "xlsx",
       "National Security System categorization worksheet.",
       "ISSO", ["NSS designation", "Classification level"],
       "ISSO drafts; ISSM approves.",
       ["RA-2"],
       ["CNSSI 1253 worksheet completed"],
       "Required only for NSS. Approved before Step 2.",
       "Categorization > CNSSI 1253"),
    _t("categorization_rationale", "Categorization Rationale Narrative", "categorize", "docx",
       "Narrative justifying the impact level decision and any deviations.",
       "ISSO", ["FIPS 199 worksheet", "Mission analysis"],
       "ISSO drafts; ISSM reviews.",
       ["RA-2"],
       ["Rationale narrative attached to FIPS 199 worksheet"],
       "Narrative addresses each CIA dimension and overall.",
       "Categorization > Rationale"),
    
    # ---------- Step 2 - Select ----------
    _t("control_responsibility_matrix", "Control Responsibility Matrix (CRM)", "select", "xlsx",
       "Identify the responsible role for every selected control.",
       "ISSO", ["Selected control set", "Role assignments"],
       "ISSO drafts; ISSM approves.",
       ["PM-2", "AC-2"],
       ["Matrix mapping every control to a role"],
       "All selected controls have an assigned owner.",
       "Selection > CRM"),
    _t("control_artifact_matrix", "Control Artifact Matrix (CAM)", "select", "xlsx",
       "For each control, list required artifacts and where they live in eMASS.",
       "ISSO", ["Selected control set", "Artifact list"],
       "ISSO drafts.",
       ["CA-1"],
       ["Matrix with control, artifact, eMASS location"],
       "Every control has at least one artifact mapped.",
       "Selection > CAM"),
    _t("tailored_baseline", "Tailored Baseline Selection", "select", "docx",
       "800-53B baseline with documented additions, removals, scoping, and compensations.",
       "ISSO", ["FIPS 199 result", "Overlays"],
       "ISSO drafts; SCA reviews.",
       ["RA-2", "PL-2"],
       ["Baseline list with tailoring rationale"],
       "Tailoring decisions documented per control.",
       "Selection > Baseline"),
    _t("overlay_application", "Overlay Application Worksheet", "select", "docx",
       "Document overlays (CUI, Privacy, NSS, etc.) applied to the baseline.",
       "ISSO", ["Applicable overlays"],
       "ISSO drafts; ISSM approves.",
       ["PL-2"],
       ["Overlay applicability statement"],
       "All applicable overlays applied or explicitly waived.",
       "Selection > Overlays"),
    
    # ---------- Step 3 - Implement ----------
    _t("ssp", "System Security Plan (SSP)", "implement", "docx",
       "Authoritative document describing the system, boundary, categorization, control implementation, and roles.",
       "ISSO",
       ["System metadata", "Boundary description", "FIPS 199 result",
        "Implemented controls", "Roles and responsibilities"],
       "ISSO drafts; ISSM reviews; AO accepts.",
       ["PL-2", "PL-4", "AC-1"],
       ["Approved SSP document",
        "Implementation statements for all in-scope controls"],
       "All control implementation statements written, evidence linked.",
       "SSP > Master Document",
       generator="ssp"),
        _t("topology_diagram", "Network Topology Diagram", "implement", "pdf",
       "Visual representation of the system network, segments, and trust zones.",
       "Network Engineer", ["Network design", "Segment list"],
       "Network Engineer drafts; ISSO approves.",
       ["SC-7", "PL-2"],
       ["Topology diagram (PDF or image embedded in SSP)"],
       "Diagram matches current production state.",
       "SSP > Topology"),
    _t("data_flow_diagram", "Data Flow Diagram", "implement", "pdf",
       "Diagram of data flows including inputs, outputs, storage, and external interfaces.",
       "ISSO", ["Architecture", "Data inventory"],
       "ISSO drafts; ISSM reviews.",
       ["AC-4", "SC-7"],
       ["Diagram showing direction and protocol"],
       "Every data type from FIPS 199 traced through the diagram.",
       "SSP > Data Flow"),
    _t("authorization_boundary_diagram", "Authorization Boundary Diagram", "implement", "pdf",
       "Diagram showing exactly what is and is not within the authorization boundary.",
       "ISSO", ["Boundary description", "Topology"],
       "ISSO drafts; ISSM approves.",
       ["PL-2", "CA-3"],
       ["Boundary diagram with components labeled in/out"],
       "Boundary matches the SSP description.",
       "SSP > Boundary Diagram"),
    _t("ppsm_worksheet", "Ports, Protocols, and Services Management (PPSM)", "implement", "xlsx",
       "List of every port, protocol, and service authorized through the boundary.",
       "Network Engineer", ["Firewall rules", "Application list"],
       "Network Engineer drafts; ISSO approves.",
       ["CM-7", "SC-7"],
       ["PPSM matrix with justification per entry"],
       "Every authorized port/protocol/service justified.",
       "SSP > PPSM"),
    _t("hardware_inventory", "Hardware Inventory", "implement", "xlsx",
       "List of every hardware component within the authorization boundary.",
       "Sysadmin", ["Discovery scan", "Asset records"],
       "Sysadmin drafts; ISSO reviews.",
       ["CM-8"],
       ["HW inventory CSV/XLSX export"],
       "Inventory reconciled to discovery scan.",
       "Inventory > Hardware",
       generator="hardware_inventory"),
    _t("software_inventory", "Software Inventory", "implement", "xlsx",
       "List of every software component within the authorization boundary.",
       "Sysadmin", ["Discovery scan", "Asset records"],
       "Sysadmin drafts; ISSO reviews.",
       ["CM-8", "SA-4"],
       ["SW inventory CSV/XLSX export"],
       "Inventory reconciled to discovery scan.",
       "Inventory > Software",
       generator="software_inventory"),
    _t("firmware_inventory", "Firmware Inventory", "implement", "xlsx",
       "List of every firmware component within the authorization boundary.",
       "Sysadmin", ["Vendor records"],
       "Sysadmin drafts.",
       ["CM-8"],
       ["Firmware list with versions"],
       "All hardware components have firmware version recorded.",
       "Inventory > Firmware"),
    _t("sbom", "Software Bill of Materials (SBOM)", "implement", "xlsx",
       "Component-level SBOM including licenses and origins.",
       "SCRM Analyst", ["Build manifests", "Dependency scan"],
       "SCRM Analyst drafts.",
       ["SR-3", "SR-4", "CM-8"],
       ["SBOM in standard format (CycloneDX or SPDX)"],
       "SBOM regenerated each release.",
       "Inventory > SBOM"),
    _t("rules_of_behavior", "Rules of Behavior (ROB)", "implement", "docx",
       "User behavior expectations and consequences.",
       "ISSO", ["Org policy template"],
       "ISSO drafts; ISSM approves.",
       ["PL-4"],
       ["ROB document; user acknowledgements"],
       "Every user acknowledges ROB within 30 days of access.",
       "SSP > ROB"),
    _t("config_management_plan", "Configuration Management Plan", "implement", "docx",
       "Defines change-control process, baseline management, and approval body.",
       "Config Manager", ["CM Policy", "CCB charter"],
       "Config Manager drafts; ISSO approves.",
       ["CM-1", "CM-3"],
       ["CMP document with CCB definition"],
       "Plan signed and CCB minutes available.",
       "CMP > Master Document"),
    _t("isa", "Interconnection Security Agreement (ISA)", "implement", "docx",
       "Agreement governing data exchange with another system.",
       "ISSO (both sides)",
       ["Connection requirements", "Other system AO"],
       "Both ISSOs and AOs sign.",
       ["CA-3"],
       ["Signed ISA on file"],
       "Active ISA per external connection.",
       "Connections > ISAs"),
    
    # ---------- Step 4 - Assess ----------
    _t("sap", "Security Assessment Plan (SAP)", "assess", "docx",
       "Plan defining scope, methods, schedule, and assessor for the assessment.",
       "SCA", ["Selected control set", "Assessment scope"],
       "SCA drafts; AO approves.",
       ["CA-2"],
       ["Approved SAP signed by AO"],
       "SAP signed before any control test starts.",
       "Assessment > SAP"),
    _t("sar", "Security Assessment Report (SAR)", "assess", "docx",
       "Report capturing assessment results, findings, and recommendations.",
       "SCA", ["Assessment results", "Test artifacts"],
       "SCA drafts; ISSM reviews; AO accepts.",
       ["CA-2"],
       ["SAR document with finding-level detail"],
       "SAR delivered before authorization decision.",
       "Assessment > SAR"),
        _t("vuln_scan_trend", "Vulnerability Scan Trend Report", "assess", "xlsx",
       "Trend of Critical / High / Medium / Low findings across recent scans.",
       "Vulnerability Analyst", ["ACAS scan history"],
       "Analyst generates monthly.",
       ["RA-5"],
       ["Trend chart with last 6 scans"],
       "Latest report < 30 days old.",
       "Assessment > Vuln Trend",
       generator="vuln_trend"),
        _t("risk_register", "Risk Register", "assess", "xlsx",
       "Aggregated residual risks for AO review.",
       "ISSO", ["SAR findings", "POA&M list"],
       "ISSO drafts; ISSM reviews.",
       ["RA-3", "PM-9"],
       ["Risk register with likelihood and impact"],
       "Each finding traced to a risk and a POA&M.",
       "Assessment > Risk Register"),

    # ---------- Step 5 - Authorize ----------
    _t("ato_readiness_checklist", "ATO Readiness Checklist", "authorize", "docx",
       "Confirms every package artifact is present, signed, and uploaded.",
       "ISSO", ["Package artifact list"],
       "ISSO completes; ISSM verifies.",
       ["CA-6"],
       ["Checklist with artifact status"],
       "All required artifacts present and signed.",
       "Authorization > Readiness"),
    _t("executive_risk_summary", "Executive Risk Summary", "authorize", "docx",
       "One-page summary for the AO covering posture and residual risk.",
       "ISSM", ["Risk register", "POA&M summary"],
       "ISSM drafts; AO reads.",
       ["RA-3"],
       ["One-page summary"],
       "Summary < 1 page, free of jargon, includes recommendation.",
       "Authorization > Risk Summary"),
    _t("residual_risk_statement", "Residual Risk Statement", "authorize", "docx",
       "Statement on each accepted residual risk.",
       "ISSM", ["Risk register"],
       "ISSM drafts; AO accepts.",
       ["RA-3"],
       ["Per-risk acceptance language"],
       "Each residual risk has a signed acceptance statement.",
       "Authorization > Residual Risk"),
    _t("ao_decision_doc", "AO Authorization Decision Document", "authorize", "docx",
       "Formal AO decision: ATO, IATT, denial, or extension.",
       "AO", ["Risk summary", "SAR", "POA&M"],
       "AO signs.",
       ["CA-6"],
       ["Signed AO decision document"],
       "Decision date, conditions, and expiration recorded.",
       "Authorization > Decision"),
    _t("ato_conditions_tracker", "ATO Conditions Tracker", "authorize", "xlsx",
       "Tracker for each AO-imposed condition until satisfied.",
       "ISSO", ["AO decision document"],
       "ISSO maintains; ISSM reviews monthly.",
       ["CA-6"],
       ["Tracker with status per condition"],
       "Every AO condition has a milestone date and status.",
       "Authorization > Conditions"),

    # ---------- Step 6 - Monitor ----------
    _t("conmon_plan", "Continuous Monitoring Plan", "monitor", "docx",
       "Defines metrics, frequencies, and ongoing assessments per CA-7.",
       "ISSO", ["Control set", "Vulnerability scan plan"],
       "ISSO drafts; ISSM approves.",
       ["CA-7"],
       ["ConMon Plan document"],
       "Plan reviewed annually; metrics tracked.",
       "ConMon > Plan"),
    _t("monthly_cyber_status", "Monthly Cyber Status Report", "monitor", "docx",
       "Standard format covering posture, findings, and POA&M aging.",
       "ISSO", ["POA&M register", "Scan trends"],
       "ISSO drafts; ISSM signs.",
       ["CA-7"],
       ["Monthly report"],
       "Delivered each month within 5 business days of close.",
       "ConMon > Monthly Status"),
    _t("annual_assessment_record", "Annual Control Assessment Record", "monitor", "xlsx",
       "Subset of controls re-tested each year per CA-7 sampling plan.",
       "ISSO / SCA", ["ConMon plan", "Sampling list"],
       "SCA documents results; ISSO reviews.",
       ["CA-7"],
       ["Annual sampling record with results"],
       "Sample completed each year per plan.",
       "ConMon > Annual Sampling"),
    _t("incident_after_action", "Incident Response After-Action Report", "monitor", "docx",
       "Post-incident review documenting timeline, root cause, and lessons.",
       "ISSO", ["Incident timeline", "Tickets"],
       "ISSO drafts; ISSM signs.",
       ["IR-4"],
       ["After-action document"],
       "After-action complete within 30 days of incident close.",
       "ConMon > Incident After-Actions"),

    # ---------- Cross-step ----------
    _t("poam_register", "POA&M Register", "ongoing", "xlsx",
       "Plan of Action and Milestones register tracked through the lifecycle.",
       "ISSO", ["Findings", "Vulnerabilities", "Closure evidence"],
       "ISSO maintains; ISSM approves closures.",
       ["CA-5"],
       ["POA&M register exported to eMASS-aligned columns"],
       "Register updated within 5 days of any finding change.",
       "POA&M > Register",
       generator="poam_register"),
    _t("contingency_plan", "Contingency Plan", "ongoing", "docx",
       "Recovery plan with essential missions, RTO/RPO, and exercise records.",
       "ISSO", ["BIA", "Backup procedures"],
       "ISSO drafts; ISSM approves.",
       ["CP-2"],
       ["Approved CP document; exercise after-action"],
       "Plan tested annually.",
       "Contingency > Plan"),
    _t("incident_response_plan", "Incident Response Plan", "ongoing", "docx",
       "Defines how the organization detects, contains, and recovers from incidents.",
       "ISSO", ["Org IR policy", "Playbooks"],
       "ISSO drafts; ISSM approves.",
       ["IR-1", "IR-4"],
       ["IR Plan document"],
       "Plan exercised annually.",
       "IR > Plan"),
    _t("privacy_impact_assessment", "Privacy Impact Assessment (PIA)", "ongoing", "docx",
       "Documents PII processing purposes, flows, and controls.",
       "Privacy Officer", ["Data inventory", "PII flows"],
       "Privacy Officer drafts; ISSM reviews.",
       ["PT-3"],
       ["Approved PIA"],
       "Required if system processes PII; updated on change.",
       "Privacy > PIA"),
    _t("privacy_threshold_analysis", "Privacy Threshold Analysis (PTA)", "ongoing", "docx",
       "Determines whether a PIA is required.",
       "Privacy Officer", ["System description", "Data flows"],
       "Privacy Officer drafts.",
       ["PT-1"],
       ["PTA decision record"],
       "Completed before any system change involving PII.",
       "Privacy > PTA"),
]


def get_template(key):
    for t in TEMPLATES:
        if t["key"] == key:
            return t
    return None
