"""
Curated subset of NIST SP 800-53 Rev. 5 controls used to seed the
ControlCatalog table for prototype demonstration. About 60 controls covering
every one of the 20 control families, with the most-cited foundational
controls per family.

NOTE: control statements are paraphrased summaries for illustration. The
authoritative text is in NIST SP 800-53 Rev. 5. Any operational use of this
catalog must be reconciled against the official publication and any relevant
overlays / DoD CCI mappings.
"""

FAMILIES = {
    "AC": "Access Control",
    "AT": "Awareness and Training",
    "AU": "Audit and Accountability",
    "CA": "Assessment, Authorization, and Monitoring",
    "CM": "Configuration Management",
    "CP": "Contingency Planning",
    "IA": "Identification and Authentication",
    "IR": "Incident Response",
    "MA": "Maintenance",
    "MP": "Media Protection",
    "PE": "Physical and Environmental Protection",
    "PL": "Planning",
    "PM": "Program Management",
    "PS": "Personnel Security",
    "PT": "PII Processing and Transparency",
    "RA": "Risk Assessment",
    "SA": "System and Services Acquisition",
    "SC": "System and Communications Protection",
    "SI": "System and Information Integrity",
    "SR": "Supply Chain Risk Management",
}


def _c(nist_id, title, low, mod, high, type_default, statement,
       artifacts, evidence, methods, roles, emass, mistakes, poam, conmon,
       rmf_step=3):
    family = nist_id.split("-")[0]
    return {
        "nist_id": nist_id,
        "title": title,
        "family": family,
        "family_name": FAMILIES.get(family, family),
        "baseline_low": low,
        "baseline_mod": mod,
        "baseline_high": high,
        "control_type_default": type_default,
        "rmf_step": rmf_step,
        "statement": statement,
        "expected_artifacts": artifacts,
        "evidence_examples": evidence,
        "assessment_methods": methods,
        "responsible_roles": roles,
        "emass_location": emass,
        "common_mistakes": mistakes,
        "poam_triggers": [poam] if isinstance(poam, str) else list(poam),
        "conmon_metric": conmon,
    }


# ----- Access Control (AC) -----
CATALOG = [
    _c("AC-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate access control policy and procedures, and review them on a defined frequency.",
       ["Access Control Policy", "Access Control Procedures"],
       ["Signed policy document", "Procedure review log", "Distribution record"],
       ["Examine", "Interview"],
       ["ISSO", "ISSM"],
       "Controls > AC-1 > Policy",
       ["Policy never reviewed after initial sign", "No procedures supporting the policy", "Distribution not documented"],
       "No signed policy on file or > 3 years since review",
       "Annual policy review tracked"),
    _c("AC-2", "Account Management",
       True, True, True, "system",
       "Define account types, establish conditions for membership, identify approvers, manage the account lifecycle, and review accounts on a defined frequency.",
       ["Account Management Procedure", "Account Inventory", "Account Review Records"],
       ["Account export from IAM", "Periodic review attestation", "Account approval records"],
       ["Examine", "Interview", "Test"],
       ["Sysadmin", "ISSO"],
       "Controls > AC-2 > Implementation",
       ["Stale shared accounts", "No quarterly review evidence", "Manual account creation without ticket trail"],
       "Account review missed for > 90 days",
       "Monthly account-review attestation"),
    _c("AC-3", "Access Enforcement",
       True, True, True, "system",
       "Enforce approved authorizations for logical access to information and system resources.",
       ["Access Enforcement Configuration", "Authorization Matrix"],
       ["IAM policy export", "Permission audit log", "Test results showing denied unauthorized access"],
       ["Examine", "Test"],
       ["Sysadmin", "ISSO"],
       "Controls > AC-3 > Implementation",
       ["Group policies that grant broader access than authorized", "No deny-by-default rule"],
       "Test shows enforcement bypass",
       "Quarterly access enforcement test"),
    _c("AC-6", "Least Privilege",
       False, True, True, "system",
       "Employ the principle of least privilege, allowing only authorized accesses for users which are necessary to accomplish assigned tasks.",
       ["Least Privilege Procedure", "Privileged Account Inventory"],
       ["Privileged account list", "Role definitions", "Access review"],
       ["Examine", "Interview", "Test"],
       ["ISSO", "Sysadmin"],
       "Controls > AC-6 > Implementation",
       ["Standing admin access for daily users", "No separation between user and admin roles"],
       "Privileged accounts > 5% of user base without justification",
       "Privileged account ratio tracked monthly"),
    _c("AC-7", "Unsuccessful Logon Attempts",
       True, True, True, "system",
       "Enforce a limit on consecutive invalid logon attempts and lock the account or session for a defined period.",
       ["Logon Lockout Configuration"],
       ["Auth policy export", "Lockout test results"],
       ["Examine", "Test"],
       ["Sysadmin"],
       "Controls > AC-7 > Implementation",
       ["Lockout duration too short", "No lockout on service accounts"],
       "Test shows lockout not enforced",
       "Lockout config audited quarterly"),
    _c("AC-17", "Remote Access",
       True, True, True, "system",
       "Establish and enforce usage restrictions, configuration requirements, and authorization for each type of remote access.",
       ["Remote Access Policy", "VPN Configuration"],
       ["VPN config", "MFA logs", "Approved remote access list"],
       ["Examine", "Test"],
       ["Network Engineer", "ISSO"],
       "Controls > AC-17 > Implementation",
       ["Remote access without MFA", "Split tunnel allowed without justification"],
       "Remote session without MFA",
       "Daily VPN MFA-failure rate"),

    # ----- Awareness and Training (AT) -----
    _c("AT-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate security awareness and training policy and procedures.",
       ["AT Policy", "AT Procedures"],
       ["Signed policy", "Annual review log"],
       ["Examine"],
       ["ISSM"],
       "Controls > AT-1 > Policy",
       ["No formal procedure for tracking training due dates"],
       "Policy older than 3 years",
       "Annual policy review"),
    _c("AT-2", "Literacy Training and Awareness",
       True, True, True, "common",
       "Provide security awareness training to system users on initial assignment and on a defined frequency thereafter.",
       ["Annual Awareness Training Curriculum", "Training Completion Records"],
       ["Course completion report", "Sign-in sheets", "LMS export"],
       ["Examine", "Interview"],
       ["ISSM"],
       "Controls > AT-2 > Records",
       ["Roster not reconciled to active users", "Late completers not tracked"],
       "Training delinquent > 30 days for any user",
       "Monthly training completion rate"),
    _c("AT-3", "Role-Based Training",
       True, True, True, "common",
       "Provide role-based security training to personnel with assigned security roles before granting access.",
       ["Role-Based Training Plan"],
       ["Privileged user training records"],
       ["Examine", "Interview"],
       ["ISSM", "ISSO"],
       "Controls > AT-3 > Records",
       ["Privileged users without role-based training before access"],
       "Privileged user without RBT on access date",
       "Quarterly RBT compliance review"),

    # ----- Audit and Accountability (AU) -----
    _c("AU-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate audit and accountability policy and procedures.",
       ["AU Policy", "AU Procedures"],
       ["Signed policy"],
       ["Examine"],
       ["ISSO"],
       "Controls > AU-1 > Policy",
       ["No retention period defined in policy"],
       "Policy missing retention requirement",
       "Annual policy review"),
    _c("AU-2", "Event Logging",
       True, True, True, "system",
       "Identify the types of events the system is capable of logging and select those that must be audited.",
       ["Audit Event List", "Audit Configuration"],
       ["Event list document", "Sample audit log records"],
       ["Examine", "Test"],
       ["Sysadmin", "ISSO"],
       "Controls > AU-2 > Implementation",
       ["Logging not enabled on auth events", "No coverage of privileged commands"],
       "Required audit event class missing",
       "Daily log volume by event class"),
    _c("AU-3", "Content of Audit Records",
       True, True, True, "system",
       "Ensure audit records contain information that establishes what occurred, who or what caused it, the source, and the outcome.",
       ["Audit Record Specification"],
       ["Sample log records covering required fields"],
       ["Examine", "Test"],
       ["Sysadmin"],
       "Controls > AU-3 > Implementation",
       ["Logs missing user identifier or outcome"],
       "Sample log missing required field",
       "Quarterly audit-content review"),
    _c("AU-9", "Protection of Audit Information",
       True, True, True, "system",
       "Protect audit information and audit logging tools from unauthorized access, modification, and deletion.",
       ["Audit Storage Hardening", "Access Control on Audit Tools"],
       ["Permissions screenshot", "Storage encryption attestation"],
       ["Examine", "Test"],
       ["Sysadmin", "ISSO"],
       "Controls > AU-9 > Implementation",
       ["Application admins can clear logs", "Audit volume not encrypted at rest"],
       "Audit data writable by non-audit role",
       "Quarterly audit ACL review"),
    _c("AU-11", "Audit Record Retention",
       True, True, True, "common",
       "Retain audit records for a defined period to provide support for after-the-fact investigations and to meet regulatory requirements.",
       ["Retention Policy"],
       ["Retention configuration", "Sample retrieval of old record"],
       ["Examine"],
       ["ISSO"],
       "Controls > AU-11 > Implementation",
       ["Retention shorter than required by org policy"],
       "Retention misconfigured",
       "Annual retention sampling"),

    # ----- Assessment, Authorization, and Monitoring (CA) -----
    _c("CA-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate assessment and authorization policy and procedures.",
       ["CA Policy", "CA Procedures"],
       ["Signed policy"],
       ["Examine"],
       ["ISSM"],
       "Controls > CA-1 > Policy",
       ["No internal pre-assessment process described"],
       "Policy missing self-assessment cadence",
       "Annual policy review"),
    _c("CA-2", "Control Assessments",
       True, True, True, "system",
       "Develop, review, and approve a security assessment plan and assess controls in accordance with the plan.",
       ["SAP", "SAR"],
       ["Signed SAP", "Completed SAR"],
       ["Examine", "Interview", "Test"],
       ["SCA", "ISSO"],
       "Controls > CA-2 > Documents",
       ["SAP scope misaligned with control set", "Findings without recommended actions"],
       "SAR overdue for annual subset",
       "Annual control sampling completion"),
    _c("CA-3", "Information Exchange",
       False, True, True, "system",
       "Approve and manage exchange of information between the system and other systems via interconnections.",
       ["ISA", "MOU"],
       ["Signed ISA/MOU", "Boundary diagram with interconnections"],
       ["Examine"],
       ["ISSO", "Network Engineer"],
       "Controls > CA-3 > ISAs",
       ["External connection without ISA", "ISA expired"],
       "Connection without active ISA",
       "Quarterly interconnection inventory"),
    _c("CA-5", "Plan of Action and Milestones",
       True, True, True, "common",
       "Develop and maintain a POA&M for the system to document planned remediation actions for findings.",
       ["POA&M Register"],
       ["Current POA&M export", "Milestone updates"],
       ["Examine"],
       ["ISSO", "ISSM"],
       "Controls > CA-5 > POA&M",
       ["POA&M not updated after assessment", "Milestones lack measurable dates"],
       "POA&M not updated after SAR",
       "POA&M aging report monthly"),
    _c("CA-7", "Continuous Monitoring",
       True, True, True, "common",
       "Develop and implement a continuous monitoring strategy that includes metrics, frequencies, and ongoing assessments.",
       ["ConMon Plan"],
       ["Monthly status reports", "Scan cadence evidence"],
       ["Examine", "Interview"],
       ["ISSO", "ISSM"],
       "Controls > CA-7 > Strategy",
       ["ConMon plan exists but is not executed", "No defined metrics"],
       "Scan cadence missed",
       "Monthly cyber status report"),

    # ----- Configuration Management (CM) -----
    _c("CM-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate configuration management policy and procedures.",
       ["CM Policy", "CM Procedures"],
       ["Signed policy"],
       ["Examine"],
       ["Config Manager", "ISSO"],
       "Controls > CM-1 > Policy",
       ["No change-control body identified"],
       "Policy missing CCB definition",
       "Annual policy review"),
    _c("CM-2", "Baseline Configuration",
       True, True, True, "system",
       "Develop, document, and maintain a current baseline configuration of the system.",
       ["Baseline Configuration Document"],
       ["Baseline export", "Diff between current and baseline"],
       ["Examine", "Test"],
       ["Sysadmin", "Config Manager"],
       "Controls > CM-2 > Baseline",
       ["Baseline never re-issued after major change"],
       "Baseline last updated > 1 year ago after major change",
       "Quarterly baseline drift report"),
    _c("CM-6", "Configuration Settings",
       True, True, True, "system",
       "Establish and document configuration settings for system components consistent with applicable benchmarks.",
       ["Configuration Settings Document", "STIG Compliance Reports"],
       ["STIG checklist", "SCAP scan results"],
       ["Examine", "Test"],
       ["Sysadmin"],
       "Controls > CM-6 > STIG",
       ["Open CAT I findings on production hosts"],
       "Open CAT I STIG finding",
       "Monthly STIG compliance %"),
    _c("CM-7", "Least Functionality",
       True, True, True, "system",
       "Configure the system to provide only essential capabilities, restricting unnecessary functions, ports, protocols, and services.",
       ["PPSM Worksheet"],
       ["Allowed services list", "Port scan results"],
       ["Examine", "Test"],
       ["Sysadmin", "Network Engineer"],
       "Controls > CM-7 > PPSM",
       ["Default services left running", "PPSM not updated"],
       "Unnecessary service identified by scan",
       "Quarterly port scan diff"),
    _c("CM-8", "System Component Inventory",
       True, True, True, "system",
       "Develop and maintain an inventory of system components that accurately reflects the current state.",
       ["Hardware Inventory", "Software Inventory"],
       ["Inventory CSV", "Discovery scan reconciliation"],
       ["Examine", "Test"],
       ["Sysadmin", "ISSO"],
       "Controls > CM-8 > Inventory",
       ["Inventory not reconciled to discovery scans"],
       "Inventory drift > 5% from discovery",
       "Monthly inventory reconciliation"),

    # ----- Contingency Planning (CP) -----
    _c("CP-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate contingency planning policy and procedures.",
       ["CP Policy"],
       ["Signed policy"],
       ["Examine"],
       ["ISSM"],
       "Controls > CP-1 > Policy",
       ["No defined RTO/RPO in policy"],
       "Policy missing RTO/RPO",
       "Annual policy review"),
    _c("CP-2", "Contingency Plan",
       True, True, True, "system",
       "Develop a contingency plan for the system that identifies essential missions and business functions and recovery objectives.",
       ["Contingency Plan", "BIA"],
       ["Approved CP document", "Tabletop exercise after-action"],
       ["Examine", "Interview"],
       ["ISSO", "System Owner"],
       "Controls > CP-2 > Plan",
       ["CP never tested", "BIA outdated"],
       "CP not tested in last year",
       "Annual CP test attestation"),
    _c("CP-9", "System Backup",
       True, True, True, "system",
       "Conduct backups of user-level and system-level information at a defined frequency and protect their confidentiality and integrity.",
       ["Backup Procedure", "Restore Test Records"],
       ["Backup logs", "Successful restore test"],
       ["Examine", "Test"],
       ["Sysadmin"],
       "Controls > CP-9 > Backup",
       ["Restore never tested", "Backups not encrypted"],
       "Restore test failure",
       "Quarterly restore test"),

    # ----- Identification and Authentication (IA) -----
    _c("IA-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate identification and authentication policy and procedures.",
       ["IA Policy"],
       ["Signed policy"],
       ["Examine"],
       ["ISSM"],
       "Controls > IA-1 > Policy",
       ["No password policy alignment with NIST SP 800-63"],
       "Policy missing 800-63 alignment",
       "Annual policy review"),
    _c("IA-2", "Identification and Authentication (Users)",
       True, True, True, "system",
       "Uniquely identify and authenticate organizational users and processes acting on behalf of users.",
       ["Authentication Configuration"],
       ["MFA enrollment report", "CAC/PIV verification logs"],
       ["Examine", "Test"],
       ["Sysadmin", "ISSO"],
       "Controls > IA-2 > Implementation",
       ["MFA not enforced for privileged accounts", "Shared service accounts"],
       "Privileged user without MFA",
       "MFA enrollment % (target 100)"),
    _c("IA-5", "Authenticator Management",
       True, True, True, "system",
       "Manage system authenticators, including initial issuance, periodic refresh, revocation, and protection.",
       ["Authenticator Management Procedure"],
       ["CAC issuance records", "Password change logs"],
       ["Examine", "Test"],
       ["Sysadmin"],
       "Controls > IA-5 > Implementation",
       ["No defined refresh cadence", "Default credentials still active"],
       "Default credentials detected",
       "Quarterly authenticator refresh"),

    # ----- Incident Response (IR) -----
    _c("IR-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate incident response policy and procedures.",
       ["IR Policy"],
       ["Signed policy"],
       ["Examine"],
       ["ISSM"],
       "Controls > IR-1 > Policy",
       ["No 24/7 reporting path defined"],
       "Policy missing reporting path",
       "Annual policy review"),
    _c("IR-4", "Incident Handling",
       True, True, True, "system",
       "Implement an incident handling capability for incidents consistent with the IR plan.",
       ["IR Plan", "Playbooks"],
       ["IR exercise after-action", "Incident tickets"],
       ["Examine", "Interview", "Test"],
       ["ISSO"],
       "Controls > IR-4 > Plan",
       ["No tabletop exercise within last year"],
       "IR exercise overdue",
       "Annual IR exercise"),
    _c("IR-6", "Incident Reporting",
       True, True, True, "common",
       "Require personnel to report suspected security incidents within the organizational reporting timeframe.",
       ["Reporting Procedure"],
       ["Sample incident report timeline"],
       ["Examine", "Interview"],
       ["ISSO"],
       "Controls > IR-6 > Reporting",
       ["Reporting deadlines missed"],
       "Late incident report",
       "Mean time to report"),

    # ----- Maintenance (MA) -----
    _c("MA-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate system maintenance policy and procedures.",
       ["MA Policy"],
       ["Signed policy"],
       ["Examine"],
       ["ISSM"],
       "Controls > MA-1 > Policy",
       ["No coverage for vendor-performed maintenance"],
       "Policy missing vendor maintenance section",
       "Annual policy review"),
    _c("MA-4", "Nonlocal Maintenance",
       False, True, True, "system",
       "Approve and monitor nonlocal maintenance and diagnostic activities.",
       ["Nonlocal Maintenance Approval Records"],
       ["Approval tickets", "Vendor session logs"],
       ["Examine", "Test"],
       ["ISSO", "Sysadmin"],
       "Controls > MA-4 > Nonlocal",
       ["Vendor sessions without prior approval"],
       "Unapproved nonlocal session",
       "Quarterly nonlocal session review"),

    # ----- Media Protection (MP) -----
    _c("MP-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate media protection policy and procedures.",
       ["MP Policy"],
       ["Signed policy"],
       ["Examine"],
       ["ISSM"],
       "Controls > MP-1 > Policy",
       ["No coverage for portable media"],
       "Policy missing portable media",
       "Annual policy review"),
    _c("MP-6", "Media Sanitization",
       True, True, True, "system",
       "Sanitize digital and non-digital media prior to disposal, release out of organizational control, or release for reuse.",
       ["Sanitization Procedure", "Sanitization Log"],
       ["Sanitization certificates"],
       ["Examine"],
       ["Sysadmin"],
       "Controls > MP-6 > Sanitization",
       ["Disposal without sanitization certificate"],
       "Disposal without sanitization",
       "Quarterly sanitization audit"),
    _c("MP-7", "Media Use",
       True, True, True, "system",
       "Restrict the use of portable storage devices in organizational systems using technical controls.",
       ["Removable Media Policy"],
       ["Endpoint policy export"],
       ["Examine", "Test"],
       ["Sysadmin"],
       "Controls > MP-7 > Implementation",
       ["USB allowed without justification"],
       "Unauthorized USB use detected",
       "USB usage report monthly"),

    # ----- Physical and Environmental Protection (PE) -----
    _c("PE-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate physical and environmental protection policy and procedures.",
       ["PE Policy"],
       ["Signed policy"],
       ["Examine"],
       ["ISSM"],
       "Controls > PE-1 > Policy",
       ["No coverage of remote work locations"],
       "Policy missing remote location coverage",
       "Annual policy review"),
    _c("PE-3", "Physical Access Control",
       True, True, True, "common",
       "Enforce physical access authorizations at facility entry/exit points.",
       ["Facility Access List"],
       ["Badge access logs", "Visitor logs"],
       ["Examine", "Test"],
       ["ISSO", "Facility Manager"],
       "Controls > PE-3 > Implementation",
       ["Visitor logs incomplete"],
       "Visitor log gap",
       "Monthly visitor log review"),
    _c("PE-6", "Monitoring Physical Access",
       False, True, True, "common",
       "Monitor physical access to the facility to detect and respond to physical security incidents.",
       ["Monitoring Procedure"],
       ["CCTV retention policy", "Alarm logs"],
       ["Examine", "Test"],
       ["Facility Manager"],
       "Controls > PE-6 > Monitoring",
       ["CCTV retention shorter than policy"],
       "CCTV retention shortfall",
       "Quarterly CCTV verification"),

    # ----- Planning (PL) -----
    _c("PL-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate security planning policy and procedures.",
       ["PL Policy"],
       ["Signed policy"],
       ["Examine"],
       ["ISSM"],
       "Controls > PL-1 > Policy",
       ["SSP review cadence undefined"],
       "Policy missing SSP review cadence",
       "Annual policy review"),
    _c("PL-2", "System Security and Privacy Plan",
       True, True, True, "system",
       "Develop, review, and update a security and privacy plan for the system that aligns with the system architecture.",
       ["SSP"],
       ["Approved SSP", "SSP review log"],
       ["Examine"],
       ["ISSO"],
       "Controls > PL-2 > SSP",
       ["SSP not updated after major change"],
       "SSP outdated > 1 year after change",
       "Annual SSP review"),
    _c("PL-4", "Rules of Behavior",
       True, True, True, "common",
       "Establish and make readily available organization-defined rules of behavior for system users.",
       ["Rules of Behavior"],
       ["Signed acknowledgements"],
       ["Examine"],
       ["ISSO"],
       "Controls > PL-4 > Acknowledgements",
       ["Acknowledgements missing for new hires"],
       "ROB not signed within 30 days",
       "Quarterly ROB acknowledgement %"),

    # ----- Program Management (PM) -----
    _c("PM-1", "Information Security Program Plan",
       False, False, False, "common",
       "Develop and maintain an information security program plan and review it on a defined frequency.",
       ["Program Plan"],
       ["Signed program plan"],
       ["Examine"],
       ["ISSM"],
       "Controls > PM-1 > Program",
       ["Program plan never reviewed"],
       "Program plan stale",
       "Annual program review"),
    _c("PM-2", "Information Security Program Leadership Role",
       False, False, False, "common",
       "Appoint a senior information security officer with the responsibility to develop, implement, and maintain the information security program.",
       ["Senior ISO Appointment Letter"],
       ["Appointment letter"],
       ["Examine"],
       ["AO"],
       "Controls > PM-2 > Appointment",
       ["No current appointment letter on file"],
       "Senior ISO position vacant",
       "Annual appointment verification"),
    _c("PM-9", "Risk Management Strategy",
       False, False, False, "common",
       "Develop and implement an organization-wide risk management strategy that consistently addresses risk.",
       ["RM Strategy"],
       ["Approved strategy document"],
       ["Examine"],
       ["AO"],
       "Controls > PM-9 > Strategy",
       ["Strategy not aligned with mission"],
       "Strategy stale",
       "Annual strategy review"),

    # ----- Personnel Security (PS) -----
    _c("PS-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate personnel security policy and procedures.",
       ["PS Policy"],
       ["Signed policy"],
       ["Examine"],
       ["ISSM"],
       "Controls > PS-1 > Policy",
       ["Position risk levels not assigned"],
       "Position risk levels missing",
       "Annual policy review"),
    _c("PS-3", "Personnel Screening",
       True, True, True, "common",
       "Screen individuals prior to authorizing access to the system; rescreen consistent with policy.",
       ["Screening Procedure"],
       ["Screening completion records"],
       ["Examine"],
       ["HR Liaison"],
       "Controls > PS-3 > Screening",
       ["Access granted before screening complete"],
       "Access without completed screening",
       "Quarterly access vs. screening reconciliation"),
    _c("PS-6", "Access Agreements",
       True, True, True, "common",
       "Develop, document, and re-acknowledge access agreements at a defined frequency.",
       ["Access Agreement Template"],
       ["Signed agreements"],
       ["Examine"],
       ["ISSO"],
       "Controls > PS-6 > Agreements",
       ["Agreements not re-acknowledged annually"],
       "Agreement expired",
       "Annual re-acknowledgement %"),

    # ----- PII Processing and Transparency (PT) -----
    _c("PT-1", "Policy and Procedures",
       False, True, True, "common",
       "Develop, document, and disseminate personally identifiable information processing and transparency policy and procedures.",
       ["PT Policy"],
       ["Signed policy"],
       ["Examine"],
       ["Privacy Officer", "ISSM"],
       "Controls > PT-1 > Policy",
       ["No SORN linkage"],
       "PIA missing for PII processing",
       "Annual policy review"),
    _c("PT-3", "PII Processing Purposes",
       False, True, True, "system",
       "Document the authorized purposes for processing PII and limit processing to those purposes.",
       ["Privacy Impact Assessment"],
       ["Approved PIA", "Data flow diagram"],
       ["Examine"],
       ["Privacy Officer"],
       "Controls > PT-3 > PIA",
       ["PIA does not cover all PII fields"],
       "PII processed beyond approved purpose",
       "Quarterly PIA validation"),

    # ----- Risk Assessment (RA) -----
    _c("RA-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate risk assessment policy and procedures.",
       ["RA Policy"],
       ["Signed policy"],
       ["Examine"],
       ["ISSM"],
       "Controls > RA-1 > Policy",
       ["No defined RA frequency"],
       "Policy missing RA frequency",
       "Annual policy review"),
    _c("RA-3", "Risk Assessment",
       True, True, True, "system",
       "Conduct a risk assessment of the system and update it on a defined frequency or when major changes occur.",
       ["Risk Assessment Report"],
       ["RA report", "Update log"],
       ["Examine"],
       ["ISSO", "ISSM"],
       "Controls > RA-3 > Assessment",
       ["RA not updated after major change"],
       "RA stale after major change",
       "Annual RA review"),
    _c("RA-5", "Vulnerability Monitoring and Scanning",
       True, True, True, "system",
       "Monitor and scan for vulnerabilities at a defined frequency and remediate or mitigate identified vulnerabilities.",
       ["Vulnerability Scan Plan"],
       ["ACAS / Tenable scan results", "Scan cadence record"],
       ["Examine", "Test"],
       ["Vulnerability Analyst", "Sysadmin"],
       "Controls > RA-5 > Scanning",
       ["Scan cadence missed", "Open Critical findings beyond SLA"],
       "Open Critical finding > 30 days",
       "Weekly Critical/High finding count"),

    # ----- System and Services Acquisition (SA) -----
    _c("SA-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate system and services acquisition policy and procedures.",
       ["SA Policy"],
       ["Signed policy"],
       ["Examine"],
       ["ISSM"],
       "Controls > SA-1 > Policy",
       ["No security requirements baked into RFP template"],
       "Acquisition without security requirements",
       "Annual policy review"),
    _c("SA-4", "Acquisition Process",
       True, True, True, "common",
       "Include security and privacy functional, strength, and assurance requirements in acquisition contracts.",
       ["Acquisition Requirements Template"],
       ["Sample contract clauses"],
       ["Examine"],
       ["Contracting", "ISSO"],
       "Controls > SA-4 > Contracts",
       ["No SCRM clause", "No SBOM requirement"],
       "Contract missing security clauses",
       "Quarterly contract clause audit"),
    _c("SA-11", "Developer Testing and Evaluation",
       False, True, True, "system",
       "Require developer testing and evaluation including unit, integration, system-level, and security testing.",
       ["Developer Test Plan"],
       ["Test results", "Vulnerability scan of code"],
       ["Examine", "Test"],
       ["Developer", "ISSO"],
       "Controls > SA-11 > Testing",
       ["No SAST/DAST evidence", "Code not scanned before release"],
       "Release without security test",
       "Per-release security test"),

    # ----- System and Communications Protection (SC) -----
    _c("SC-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate system and communications protection policy and procedures.",
       ["SC Policy"],
       ["Signed policy"],
       ["Examine"],
       ["ISSM"],
       "Controls > SC-1 > Policy",
       ["No encryption standard referenced"],
       "Policy missing encryption standard",
       "Annual policy review"),
    _c("SC-7", "Boundary Protection",
       True, True, True, "system",
       "Monitor and control communications at the external boundary of the system and at key internal boundaries.",
       ["Boundary Architecture", "PPSM Worksheet"],
       ["Firewall ruleset", "Topology diagram"],
       ["Examine", "Test"],
       ["Network Engineer"],
       "Controls > SC-7 > Boundary",
       ["Any-any rules in firewall", "DMZ not enforced"],
       "Boundary control failure detected",
       "Quarterly firewall rule review"),
    _c("SC-8", "Transmission Confidentiality and Integrity",
       False, True, True, "system",
       "Protect the confidentiality and integrity of transmitted information using approved cryptography.",
       ["Encryption Configuration"],
       ["TLS version inventory", "Cert inventory"],
       ["Examine", "Test"],
       ["Sysadmin", "Network Engineer"],
       "Controls > SC-8 > Transmission",
       ["TLS 1.0 / 1.1 still enabled", "Self-signed certs in production"],
       "Weak TLS or expired cert detected",
       "Quarterly TLS scan"),
    _c("SC-12", "Cryptographic Key Establishment and Management",
       True, True, True, "system",
       "Establish and manage cryptographic keys when cryptography is used by the system.",
       ["Key Management Plan"],
       ["KMS configuration", "Rotation logs"],
       ["Examine"],
       ["Sysadmin"],
       "Controls > SC-12 > Keys",
       ["Keys never rotated", "Keys stored alongside ciphertext"],
       "Key rotation overdue",
       "Quarterly key inventory"),
    _c("SC-13", "Cryptographic Protection",
       True, True, True, "system",
       "Implement FIPS-validated or NSA-approved cryptography to protect information.",
       ["Cryptography Inventory"],
       ["FIPS 140 validation certificates"],
       ["Examine"],
       ["Sysadmin"],
       "Controls > SC-13 > FIPS",
       ["Non-FIPS cryptographic libraries in use"],
       "Non-FIPS crypto detected",
       "Annual FIPS posture review"),
    _c("SC-28", "Protection of Information at Rest",
       False, True, True, "system",
       "Protect the confidentiality and integrity of information at rest using approved cryptography.",
       ["At-Rest Encryption Configuration"],
       ["Disk encryption status", "DB encryption attestation"],
       ["Examine"],
       ["Sysadmin"],
       "Controls > SC-28 > Encryption",
       ["Database not encrypted", "Backups not encrypted"],
       "Unencrypted at-rest data identified",
       "Quarterly at-rest encryption audit"),

    # ----- System and Information Integrity (SI) -----
    _c("SI-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate system and information integrity policy and procedures.",
       ["SI Policy"],
       ["Signed policy"],
       ["Examine"],
       ["ISSM"],
       "Controls > SI-1 > Policy",
       ["No defined patch SLA"],
       "Policy missing patch SLA",
       "Annual policy review"),
    _c("SI-2", "Flaw Remediation",
       True, True, True, "system",
       "Identify, report, and correct system flaws including software flaws and patches.",
       ["Patch Management Plan"],
       ["Patch deployment logs", "Vulnerability scan trend"],
       ["Examine", "Test"],
       ["Sysadmin"],
       "Controls > SI-2 > Patching",
       ["Critical patches applied beyond SLA"],
       "Critical patch overdue",
       "Mean time to patch"),
    _c("SI-3", "Malicious Code Protection",
       True, True, True, "system",
       "Implement malicious code protection mechanisms at system entry/exit points and update them.",
       ["EDR / AV Configuration"],
       ["EDR coverage report", "Quarantine logs"],
       ["Examine", "Test"],
       ["Sysadmin"],
       "Controls > SI-3 > AV/EDR",
       ["EDR coverage gap", "Signature update lag"],
       "EDR coverage < 95%",
       "Daily EDR coverage %"),
    _c("SI-4", "System Monitoring",
       True, True, True, "system",
       "Monitor the system to detect attacks, indicators of potential attacks, and unauthorized connections.",
       ["Monitoring Architecture"],
       ["SIEM dashboards", "Alert tuning records"],
       ["Examine", "Test"],
       ["ISSO", "SOC"],
       "Controls > SI-4 > Monitoring",
       ["Critical event sources not feeding SIEM"],
       "Critical event source offline",
       "Daily ingest health"),
    _c("SI-7", "Software, Firmware, and Information Integrity",
       False, True, True, "system",
       "Employ integrity verification tools to detect unauthorized changes to software, firmware, and information.",
       ["Integrity Verification Procedure"],
       ["Integrity scan results"],
       ["Examine", "Test"],
       ["Sysadmin"],
       "Controls > SI-7 > Integrity",
       ["No baseline integrity hash"],
       "Integrity check failure",
       "Weekly integrity scan"),
    _c("SI-10", "Information Input Validation",
       False, True, True, "system",
       "Check the validity of inputs to the system to prevent injection and corruption.",
       ["Input Validation Specification"],
       ["Code review records", "WAF rules"],
       ["Examine", "Test"],
       ["Developer", "ISSO"],
       "Controls > SI-10 > Validation",
       ["No central validation library"],
       "Injection vulnerability identified",
       "Quarterly app security scan"),

    # ----- Supply Chain Risk Management (SR) -----
    _c("SR-1", "Policy and Procedures",
       True, True, True, "common",
       "Develop, document, and disseminate supply chain risk management policy and procedures.",
       ["SR Policy"],
       ["Signed policy"],
       ["Examine"],
       ["SCRM Analyst", "ISSM"],
       "Controls > SR-1 > Policy",
       ["No vendor risk tier definition"],
       "Policy missing vendor risk tiers",
       "Annual policy review"),
    _c("SR-3", "Supply Chain Controls and Processes",
       True, True, True, "common",
       "Establish a process for identifying and addressing weaknesses or deficiencies in the supply chain.",
       ["SCRM Plan"],
       ["Vendor risk register"],
       ["Examine", "Interview"],
       ["SCRM Analyst"],
       "Controls > SR-3 > Plan",
       ["No tracking of high-risk suppliers"],
       "High-risk supplier without mitigation",
       "Quarterly supplier risk review"),
    _c("SR-4", "Provenance",
       False, True, True, "system",
       "Document, monitor, and maintain valid provenance of organizational systems and components.",
       ["SBOM"],
       ["Current SBOM export", "Component pedigree"],
       ["Examine"],
       ["SCRM Analyst", "Developer"],
       "Controls > SR-4 > SBOM",
       ["SBOM not refreshed after release"],
       "SBOM stale > release cycle",
       "Per-release SBOM"),
]
